### ISSUE TITLE
Constant expected indentation for an empty line

### ISSUE THREAD

**Issue by cieraclaire** [acgd-webdev-1/content-semantics#1]
I only have 1 issue in Markbot. For the index.html - indentation, it repeatedly says that I need to have an indent of at least 4 in line 50. Once that is complete and I save, it says like 51 needs an indentation and so on and so forth. How do I get rid of that? When I go into the repository, it does not show the lines with no code. When I delete the line, move my cursor onto another line of code, and then save, it will make the empty line pop up at the bottom of the code again. I can't figure out how to attach the code to this message for you to see. (hopeless)

@thomasjbradley

**Comment by thomasjbradley** [comment]
Are you getting the validation errors in Markbot? They are likely the cause.

This is what I see when I look at your code:

![screen shot 2016-01-25 at 6 01 48 pm](https://cloud.githubusercontent.com/assets/105192/12567563/c3eac878-c38d-11e5-8279-071fbe1360d9.png)

**Comment by cieraclaire** [comment]
WOAH..Haha I feel like a nut. I think I might re-do everything so I can slowly focus on what's happening to my code.


________________________________

**Comment by cieraclaire** [comment]
I only receive errors that say please indent your code. I never received any like that :s.


________________________________

**Comment by thomasjbradley** [comment]
Hmm...

Try this newer version of Markbot and see if you get those errors:
https://www.dropbox.com/s/55a7uzj6uy3uhx8/Markbot.dmg?dl=1

**Comment by cieraclaire** [comment]
Oh wow that helped! Thanks a bunch [&#X1f60a]


________________________________

**Comment by thomasjbradley** [comment]
Sweet!
