### ISSUE TITLE
Markbot makes no sense

### ISSUE THREAD

**Issue by kyramari** [acgd-webdev-1/content-semantics#3]
So for the html-validation-fixes assignment, I fixed everything except the "airdino.jpg" file. I renamed it to air-dino.jpg and Markbot says it's wrong. 
What should I do?

@thomasjbradley

**Comment by thomasjbradley** [comment]
Did you check the name of the folder it's inside of?

**Comment by kyramari** [comment]
Ohhhhh. Thanks. That makes sense!!
