### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by Sabrinaheideman** [acgd-webdev-1/content-semantics#5]
I'm having problems with the indentation, markbot doesn't like the indentation at the end. @thomasjbradley

**Comment by thomasjbradley** [comment]
Hey!

I've used your code as a testing platform to improve Markbot.
Please download the new version and see if it helps:

https://www.dropbox.com/s/55a7uzj6uy3uhx8/Markbot.dmg?dl=0

**Comment by kyramari** [comment]
So I got the new version and I now have this problem. But when I fix in I get tons more issues. 
<img width="794" alt="screen shot 2016-01-29 at 7 59 53 am" src="https://cloud.githubusercontent.com/assets/16653506/12676259/a356f0fe-c65e-11e5-9a95-90b09150c2e0.png">

**Comment by thomasjbradley** [comment]
I just downloaded your code and walked through every error message one by one, following exactly what it told me to do. The final output is absolutely perfect.

So, just follow along, it takes a more step-by-step approach now because of how some errors can negatively influence other errors.

**Comment by kyramari** [comment]
ok thanks.
